[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "netlify-plugin-cache"

# Optional: Define any environment variables here
#[[build.environment]]
#  NODE_VERSION = "18"
